DROP SEQUENCE COMMUNITY_SEQ;
-- COMMUNITY 테이블 시퀀스 --
CREATE SEQUENCE COMMUNITY_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 0
NOCACHE
NOCYCLE;

DROP TABLE COMMUNITY_TABLE PURGE;
-- 커뮤니티 테이블 --
CREATE TABLE COMMUNITY_TABLE(
	COMMUNITY_IDX NUMBER CONSTRAINT PK_COMMUNITY PRIMARY KEY,
	COMMUNITY_SUBJECT VARCHAR2(500) NOT NULL,
	COMMUNITY_TEXT CLOB,
    COMMUNITY_FILE VARCHAR2(500),
	COMMUNITY_WRITER_IDX NUMBER NOT NULL,
    COMMUNITY_VIEW NUMBER DEFAULT 0,
    COMMUNITY_COMMENT NUMBER DEFAULT 0,
	COMMUNITY_DATE DATE NOT NULL,
    COMMUNITY_TYPE VARCHAR2(20) NOT NULL,     -- 게시판 타입 : TEXT, IMAGE, RANKING, PROMOTION	
    COMMUNITY_CATEGORY VARCHAR2(20) NOT NULL, -- 게시판 유형: all, popular, free, question, my_ranking, review, promotion
    COMMUNITY_URL VARCHAR2(500),
    COMMUNITY_THUMB VARCHAR2(500),
    COMMUNITY_UPVOTES NUMBER DEFAULT 0,  -- 업보트 수를 저장하는 컬럼
    COMMUNITY_DOWNVOTES NUMBER DEFAULT 0 -- 다운보트 수를 저장하는 컬럼
);

DROP TRIGGER community_idx_trigger;
CREATE OR REPLACE TRIGGER community_idx_trigger
BEFORE INSERT ON COMMUNITY_TABLE
FOR EACH ROW
BEGIN
  -- COMMUNITY_IDX 값이 NULL일 경우 시퀀스를 사용하여 값을 설정
  IF :NEW.COMMUNITY_IDX IS NULL THEN
    SELECT COMMUNITY_SEQ.NEXTVAL INTO :NEW.COMMUNITY_IDX FROM DUAL;
  END IF;
END;
/
DROP TABLE VOTE_HISTORY PURGE;
CREATE TABLE VOTE_HISTORY (
    ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,  -- 투표한 사용자 ID
    POST_ID NUMBER NOT NULL,  -- 투표 대상 게시물 ID, COMMUNITY_TABLE의 COMMUNITY_IDX 참조
    VOTE_TYPE VARCHAR2(10) CHECK (VOTE_TYPE IN ('UP', 'DOWN')),  -- 투표 유형 (UP 또는 DOWN)
    VOTE_DATE DATE DEFAULT SYSDATE,  -- 투표 날짜
    CONSTRAINT UNQ_USER_POST UNIQUE (USER_ID, POST_ID),
    CONSTRAINT FK_VOTE_POST FOREIGN KEY (POST_ID) REFERENCES COMMUNITY_TABLE(COMMUNITY_IDX)  -- 외래 키 제약 조건 추가
);

DROP TABLE COMMUNITY_SORT_TABLE PURGE;
--CREATE TABLE COMMUNITY_SORT_TABLE(
--    COMMUNITY_SORT_ORDER VARCHAR2(10) DEFAULT 'best' NOT NULL, -- 정렬 기준: best, latest
--    COMMUNITY_VIEW_TYPE VARCHAR2(10) DEFAULT 'compact' NOT NULL -- 뷰 타입: text, compact, card
--);

--INSERT INTO COMMUNITY_TABLE (community_idx, community_subject, community_text, community_file, community_writer_idx,
--                             community_category, community_url, community_date, community_thumb)
--        VALUES (#{community_idx}, #{community_subject}, #{community_text, jdbcType=VARCHAR}, #{community_file, jdbcType=VARCHAR},
--                #{community_writer_idx}, #{community_category}, #{community_url, jdbcType=VARCHAR}, SYSDATE, #{community_thumb, jdbcType=VARCHAR})

--@Update("UPDATE COMMUNITY_TABLE SET 
--    		COMMUNITY_SUBJECT = #{community_subject},
--            COMMUNITY_TEXT = #{community_text, jdbcType=VARCHAR},
--    		COMMUNITY_WRITER_IDX = #{community_writer_idx}, 
--            COMMUNITY_FILE = #{community_file, jdbcType=VARCHAR},
--    		COMMUNITY_DATE = SYSDATE, 
--            COMMUNITY_CATEGORY = #{community_category}, 
--            COMMUNITY_URL = #{community_url, jdbcType=VARCHAR},
--    		COMMUNITY_THUMB = #{community_thumb, jdbcType=VARCHAR}
--    		WHERE COMMUNITY_IDX = #{community_idx}
            
            
DESC COMMUNITY_TABLE;
SELECT * FROM COMMUNITY_TABLE ORDER BY COMMUNITY_IDX;
SELECT * FROM COMMUNITY_SORT_TABLE;
SELECT * FROM USER_TABLE ORDER BY USER_IDX;
DELETE FROM COMMUNITY_TABLE WHERE COMMUNITY_IDX BETWEEN 1 AND 33; 

COMMIT;

SELECT * FROM USER_TABLE WHERE USER_IDX = 1;

ALTER TABLE COMMUNITY_TABLE 
ADD COMMUNITY_UPVOTES NUMBER DEFAULT 0;

ALTER TABLE COMMUNITY_TABLE 
ADD COMMUNITY_DOWNVOTES NUMBER DEFAULT 0;

ALTER TABLE COMMUNITY_TABLE 
ADD COMMUNITY_WILSON_SCORE NUMBER DEFAULT 0;

ALTER TABLE COMMUNITY_TABLE 
ADD (COMMUNITY_COMMENT NUMBER DEFAULT 0);


UPDATE COMMUNITY_TABLE SET COMMUNITY_VIEW = COMMUNITY_VIEW + 1 WHERE COMMUNITY_IDX = 1;




