/*
    -- system 에서 세계과자프로젝트 유저 생성 --
    CREATE USER worldSnack IDENTIFIED BY 1234;
    
    -- 세션 접속 권한 부여 --
    GRANT CREATE SESSION TO worldSnack;
    
    -- 테이블 생성 권한 부여 --
    GRANT CREATE TABLE TO worldSnack;
       
    -- tablespace 할당량 권한 부여 --
    ALTER USER worldSnack DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
*/

DROP SEQUENCE USER_SEQ;
-- user 테이블 시퀀스 (24.08.14 아직 실행은 안했음) --
CREATE SEQUENCE USER_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 0;

DROP SEQUENCE CONTENT_SEQ;
-- content 테이블 시퀀스 (24.08.14 아직 실행은 안했음) --
CREATE SEQUENCE CONTENT_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 0;


DROP TABLE USER_TABLE PURGE;
-- 사용자 정보 테이블 --
CREATE TABLE USER_TABLE(
	USER_IDX NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_NAME VARCHAR2(50) NOT NULL,
	USER_ID VARCHAR2(100) NOT NULL,
	USER_PW VARCHAR2(100) NOT NULL,
    USER_EMAIL VARCHAR2(100) NOT NULL,
    USER_NICKNAME VARCHAR2(100) NOT NULL
);



DROP TABLE CONTENT_TABLE PURGE;
-- 게시글 정보 테이블 --
CREATE TABLE CONTENT_TABLE(
	CONTENT_IDX NUMBER CONSTRAINT PK_CONTENT PRIMARY KEY,
	CONTENT_SUBJECT VARCHAR2(500) NOT NULL,
	CONTENT_TEXT LONG NOT NULL,
	CONTENT_FILE VARCHAR2(500),
	CONTENT_WRITER_IDX NUMBER CONSTRAINT FK_CONTENT REFERENCES USER_TABLE(USER_IDX) NOT NULL,
    CONTENT_MAKE VARCHAR2(50) NOT NULL,
    CONTENT_COUNTRY VARCHAR2(50) NOT NULL,
    CONTENT_PRODNO VARCHAR2(10) NOT NULL,
    CONTENT_PRODPRICE NUMBER NOT NULL,
    CONTENT_VIEW NUMBER DEFAULT 0,
	CONTENT_DATE DATE NOT NULL
);


DROP SEQUENCE CATEGORY_INFO_SEQ;
-- content 테이블 시퀀스 (24.08.14 아직 실행은 안했음) --
CREATE SEQUENCE CATEGORY_INFO_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 0;


DROP TABLE CATEGORY_INFO_TABLE PURGE;
-- 카테고리 목록 테이블 --
CREATE TABLE CATEGORY_INFO_TABLE (
	CATEGORY_INFO_IDX NUMBER CONSTRAINT PK_CATEGORY_INFO PRIMARY KEY,
	CATEGORY_INFO_NAME VARCHAR2(500) NOT NULL
);



DROP TABLE CATEGORY_SELECT_TABLE;
-- 제품 검색용 분류 테이블 --
CREATE TABLE CATEGORY_SELECT_TABLE(
    CONTENT_IDX NUMBER CONSTRAINT FK_CATEGORY_SELECT 
                        REFERENCES CONTENT_TABLE(CONTENT_IDX) NOT NULL,
    CATEGORY_INFO_IDX NUMBER CONSTRAINT FK2_CATEGORY_SELECT 
                        REFERENCES CATEGORY_INFO_TABLE(CATEGORY_INFO_IDX) NOT NULL,
    CATEGORY_SELECT_NAME VARCHAR2(500)
);



DROP TABLE SCRAP_TABLE;
-- 관심/찜/공유 한 게시글 정보 테이블 --
CREATE TABLE SCRAP_TABLE (
    USER_IDX NUMBER CONSTRAINT FK_SCRAP
                        REFERENCES USER_TABLE(USER_IDX) NOT NULL,
    CONTENT_IDX NUMBER CONSTRAINT FK2_SCRAP
                        REFERENCES CONTENT_TABLE(CONTENT_IDX) NOT NULL
);



DROP TABLE LOGIN_LOG_TABLE;
-- 로그인,로그아웃 로그 저장 테이블 --
CREATE TABLE LOGIN_LOG_TABLE (
    USER_IDX NUMBER CONSTRAINT FK_LOGIN_LOG
                        REFERENCES USER_TABLE(USER_IDX) NOT NULL,
    LOGIN_START_DATE DATE,
    LOGIN_END_DATE DATE,
    LOGIN_IP_ADDR VARCHAR2(20)
);


SELECT * FROM USER_TABLE;
SELECT * FROM CONTENT_TABLE;
SELECT * FROM CATEGORY_INFO_TABLE;
SELECT * FROM CATEGORY_SELECT_TABLE;
SELECT * FROM SCRAP_TABLE;


